FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY server ./server

# Expose backend port
EXPOSE 3001

# Start backend server
CMD ["npm", "run", "server"]
